app = "lord-arbiter-backend"  # Replace with your Fly app name

primary_region = "sin"  # Replace with your closest Fly region (e.g., sin = Singapore)

[build]
  image = "python:3.11-slim"  # You can override this if you're using a Dockerfile

[env]
  DATABASE_URL = "postgres://neondb_owner:npg_ObF7l2xsqoXn@ep-weathered-sky-a1bnzynx-pooler.ap-southeast-1.aws.neon.tech/neondb?"  # Will be injected during deployment or via `fly secrets`

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/"
    protocol = "http"
