app = "lord-arbiter-backend"  # Your Fly.io app name

primary_region = "sin"        # You can change this to your nearest region

[build]
  dockerfile = "./Dockerfile" # Ensure this matches your Dockerfile name

[env]
  PORT = "8000"               # Port that Uvicorn is listening on

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [services.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
